"""
Schema definitions for all eFP databases that expose a sample_data table.

Every database shares the same three-column structure:
  data_probeset_id (VARCHAR 255), data_signal (FLOAT), data_bot_id (VARCHAR 255).

Species and probeset/gene-model classification are sourced from combined_master.json.
To add a new database, add its name to _DATABASE_NAMES (and an entry to combined_master.json
if one doesn't already exist) — no other changes needed.
"""

from __future__ import annotations

from typing import Any, Dict, List

from api.utils.bar_utils import load_combined_master

_MASTER_DATABASES = load_combined_master()["databases"]

ColumnSpec = Dict[str, Any]
DatabaseSpec = Dict[str, Any]

_SCHEMA_TEMPLATE: DatabaseSpec = {
    "table_name": "sample_data",
    "columns": [
        {"name": "data_probeset_id", "type": "string", "length": 255, "nullable": True, "primary_key": True},
        {"name": "data_signal", "type": "float", "nullable": True, "primary_key": True},
        {"name": "data_bot_id", "type": "string", "length": 255, "nullable": True, "primary_key": True},
    ],
    "index": ["data_probeset_id", "data_bot_id", "data_signal"],
    "identifier_type": "agi",
}


def _schema(species: str, charset: str = "latin1") -> DatabaseSpec:
    """Build a schema entry for one eFP database.

    :param species: Species name stored in metadata (e.g., 'arabidopsis').
    :param charset: MySQL character set — 'latin1' for most, 'utf8mb4' for non-Latin labels.
    :returns: Full database schema dict ready for model generation.
    :rtype: DatabaseSpec
    """
    return {
        **_SCHEMA_TEMPLATE,
        "charset": charset,
        "metadata": {"species": species, "sample_regex": r"^[\w.\-]+$"},
    }


# fmt: off
# Database names exposing a sample_data table (species/gene_id_class come from combined_master.json)
_DATABASE_NAMES: List[str] = [
    "actinidia_bud_development",
    "actinidia_flower_fruit_development",
    "actinidia_postharvest",
    "actinidia_vegetative_growth",
    "affydb",
    "apple",
    "arabidopsis_ecotypes",
    "arabidopsis_NIE_pseudobulk",
    "arabidopsis_flower_lee_pseudobulk",
    "arabidopsis_root_rs_pseudobulk",
    "arabidopsis_seed_martin_pseudobulk",
    "arabidopsis_silique_lee_pseudobulk",
    "arabidopsis_stem_lee_pseudobulk",
    "arachis",
    "atgenexp",
    "atgenexp_hormone",
    "atgenexp_pathogen",
    "atgenexp_plus",
    "atgenexp_stress",
    "barley_mas",
    "barley_rma",
    "barley_seed",
    "barley_spike_meristem",
    "barley_spike_meristem_v3",
    "brachypodium",
    "brachypodium_Bd21",
    "brachypodium_embryogenesis",
    "brachypodium_grains",
    "brachypodium_metabolites_map",
    "brachypodium_photo_thermocycle",
    "brassica_rapa",
    "cacao_developmental_atlas",
    "cacao_developmental_atlas_sca",
    "cacao_drought_diurnal_atlas",
    "cacao_drought_diurnal_atlas_sca",
    "cacao_infection",
    "cacao_leaf",
    "cacao_meristem_atlas_sca",
    "cacao_seed_atlas_sca",
    "camelina",
    "camelina_tpm",
    "cannabis",
    "canola",
    "canola_original",
    "canola_original_v2",
    "canola_seed",
    "cassava_atlas",
    "cassava_cbb",
    "cassava_eacmv",
    "circadian_mutants",
    "cuscuta",
    "cuscuta_early_haustoriogenesis",
    "cuscuta_lmd",
    "dna_damage",
    "durum_wheat_abiotic_stress",
    "durum_wheat_biotic_stress",
    "durum_wheat_development",
    "embryo",
    "eucalyptus",
    "euphorbia",
    "gc_drought",
    "germination",
    "grape_developmental",
    "guard_cell",
    "gynoecium",
    "heterodera_schachtii",
    "hnahal",
    "human_body_map_2",
    "human_developmental",
    "human_developmental_SpongeLab",
    "human_diseased",
    "kalanchoe",
    "kalanchoe_time_course_analysis",
    "klepikova",
    "lateral_root_initiation",
    "light_series",
    "lipid_map",
    "little_millet",
    "lupin_lcm_leaf",
    "lupin_lcm_pod",
    "lupin_lcm_stem",
    "lupin_pod_seed",
    "lupin_whole_plant",
    "maize_RMA_linear",
    "maize_RMA_log",
    "maize_atlas",
    "maize_atlas_v5",
    "maize_buell_lab",
    "maize_early_seed",
    "maize_ears",
    "maize_embryonic_leaf_development",
    "maize_enzyme",
    "maize_gdowns",
    "maize_iplant",
    "maize_kernel_v5",
    "maize_leaf_gradient",
    "maize_lipid_map",
    "maize_metabolite",
    "maize_nitrogen_use_efficiency",
    "maize_rice_comparison",
    "maize_root",
    "maize_stress_v5",
    "mangosteen_aril_vs_rind",
    "mangosteen_callus",
    "mangosteen_diseased_vs_normal",
    "mangosteen_fruit_ripening",
    "mangosteen_seed_development",
    "mangosteen_seed_development_germination",
    "mangosteen_seed_germination",
    "marchantia_organ_stress",
    "medicago_mas",
    "medicago_rma",
    "medicago_root",
    "medicago_root_v5",
    "medicago_seed",
    "meristem_db",
    "meristem_db_new",
    "mouse_db",
    "oat",
    "phelipanche",
    "physcomitrella_db",
    "poplar",
    "poplar_hormone",
    "poplar_leaf",
    "poplar_xylem",
    "potato_dev",
    "potato_stress",
    "potato_wounding",
    "rice_abiotic_stress_sc_pseudobulk",
    "rice_drought_heat_stress",
    "rice_leaf_gradient",
    "rice_maize_comparison",
    "rice_mas",
    "rice_metabolite",
    "rice_OW_pseudobulk",
    "rice_rma",
    "rice_root",
    "rohan",
    "root",
    "root_Schaefer_lab",
    "rpatel",
    "seed_db",
    "seedcoat",
    "selaginella",
    "shoot_apex",
    "silique",
    "single_cell",
    "sorghum_atlas_w_BS_cells",
    "sorghum_comparative_transcriptomics",
    "sorghum_developmental",
    "sorghum_developmental_2",
    "sorghum_flowering_activation",
    "sorghum_low_phosphorus",
    "sorghum_nitrogen_stress",
    "sorghum_nitrogen_use_efficiency",
    "sorghum_phosphate_stress",
    "sorghum_plasma",
    "sorghum_saline_alkali_stress",
    "sorghum_stress",
    "sorghum_strigolactone_variation",
    "sorghum_sulfur_stress",
    "sorghum_temperature_stress",
    "sorghum_vascularization_and_internode",
    "soybean",
    "soybean_embryonic_development",
    "soybean_heart_cotyledon_globular",
    "soybean_senescence",
    "soybean_severin",
    "spruce",
    "strawberry",
    "striga",
    "sugarcane_culms",
    "sugarcane_leaf",
    "sunflower",
    "thellungiella_db",
    "tomato",
    "tomato_ils",
    "tomato_ils2",
    "tomato_ils3",
    "tomato_meristem",
    "tomato_renormalized",
    "tomato_root",
    "tomato_root_field_pot",
    "tomato_s_pennellii",
    "tomato_seed",
    "tomato_shade_mutants",
    "tomato_shade_timecourse",
    "tomato_trait",
    "triphysaria",
    "triticale",
    "triticale_mas",
    "tung_tree",
    "wheat",
    "wheat_abiotic_stress",
    "wheat_embryogenesis",
    "wheat_meiosis",
    "wheat_root",
    "willow",
]

# Databases that use utf8mb4 charset (all others default to latin1)
_UTF8MB4 = {
    "actinidia_bud_development", "actinidia_flower_fruit_development",
    "actinidia_postharvest", "actinidia_vegetative_growth", "apple",
    "barley_seed", "barley_spike_meristem_v3",
    "brachypodium_Bd21", "brachypodium_grains", "brachypodium_metabolites_map",
    "brassica_rapa",
    "cacao_developmental_atlas", "cacao_developmental_atlas_sca",
    "cacao_drought_diurnal_atlas", "cacao_drought_diurnal_atlas_sca",
    "cacao_infection", "cacao_leaf", "cacao_meristem_atlas_sca", "cacao_seed_atlas_sca",
    "canola_seed",
    "cassava_atlas", "cassava_cbb", "cassava_eacmv",
    "circadian_mutants", "cuscuta", "cuscuta_early_haustoriogenesis", "cuscuta_lmd",
    "dna_damage",
    "durum_wheat_abiotic_stress", "durum_wheat_biotic_stress", "durum_wheat_development",
    "eucalyptus", "euphorbia",
    "gc_drought", "gynoecium", "heterodera_schachtii",
    "kalanchoe_time_course_analysis",
    "lateral_root_initiation", "lipid_map", "little_millet",
    "lupin_lcm_leaf", "lupin_lcm_pod", "lupin_lcm_stem", "lupin_pod_seed", "lupin_whole_plant",
    "maize_atlas_v5", "maize_embryonic_leaf_development", "maize_kernel_v5",
    "maize_lipid_map", "maize_nitrogen_use_efficiency", "maize_stress_v5",
    "mangosteen_aril_vs_rind", "mangosteen_callus", "mangosteen_diseased_vs_normal",
    "mangosteen_fruit_ripening", "mangosteen_seed_development",
    "mangosteen_seed_development_germination", "mangosteen_seed_germination",
    "marchantia_organ_stress",
    "medicago_root", "medicago_root_v5",
    "oat", "phelipanche", "poplar_hormone", "potato_wounding",
    "rice_abiotic_stress_sc_pseudobulk", "rice_drought_heat_stress", "rice_root",
    "silique",
    "sorghum_atlas_w_BS_cells", "sorghum_comparative_transcriptomics",
    "sorghum_developmental", "sorghum_developmental_2", "sorghum_flowering_activation",
    "sorghum_low_phosphorus", "sorghum_nitrogen_stress", "sorghum_nitrogen_use_efficiency",
    "sorghum_phosphate_stress", "sorghum_plasma", "sorghum_saline_alkali_stress",
    "sorghum_stress", "sorghum_strigolactone_variation", "sorghum_sulfur_stress",
    "sorghum_temperature_stress", "sorghum_vascularization_and_internode",
    "soybean_embryonic_development", "soybean_heart_cotyledon_globular", "soybean_senescence",
    "spruce", "strawberry",
    "sugarcane_culms", "sugarcane_leaf",
    "tomato_root", "tomato_root_field_pot", "tomato_seed",
    "tomato_shade_mutants", "tomato_shade_timecourse",
    "triphysaria",
    "wheat_abiotic_stress", "wheat_meiosis", "wheat_root",
}
# fmt: on

SIMPLE_EFP_DATABASE_SCHEMAS: Dict[str, DatabaseSpec] = {
    n: {
        **_schema(_MASTER_DATABASES[n]["species"], "utf8mb4" if n in _UTF8MB4 else "latin1"),
        **({"identifier_type": "probeset"} if _MASTER_DATABASES[n]["gene_id_class"] == "probeset" else {}),
    }
    for n in _DATABASE_NAMES
}

__all__: List[str] = ["SIMPLE_EFP_DATABASE_SCHEMAS", "ColumnSpec", "DatabaseSpec"]
